apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: todo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: ecstase/todo-app:latest
          ports:
            - containerPort: 5000
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
            - name: DB_HOST
              value: postgres
          envFrom:
            - configMapRef:
                name: web-config
          # Чтобы избежать проблем с Prometheus multiprocess dir – опционально
          # инициализируем папку /tmp
          command: ["sh", "-c", "mkdir -p /tmp && python app.py"]